### ISSUE TITLE
Request for Access to FOAP Dataset and Source Code for Academic Research

### ISSUE THREAD

**Issue by yylmm** [jflixjtu/FOAP#1]
Dear Dr. jflixjtu,

I am writing to express my admiration for your significant contributions to the field of fingerprint recognition. As a student at Sichuan University, I am deeply engaged in research within the realm of application recognition. Your work on "FOAP" (Application Fingerprint Attacks) has been a major source of inspiration and guidance in my studies.

I understand the necessity of the safeguards you have placed on your data and source code, and I fully respect these measures. They are crucial for preventing misuse and maintaining ethical research standards. In line with this, I submitted a request last month via the provided Google form to access the dataset. Unfortunately, I have not yet received a response. I am writing to reiterate my request, emphasizing my commitment to using the materials solely for academic research.

My research at Sichuan University focuses on developing advanced algorithms for enhancing the security and accuracy of application fingerprint recognition systems. This involves creating new machine learning models that can more effectively distinguish between authentic and fraudulent fingerprints in digital applications, a field that directly intersects with the themes of your "FOAP" study. Access to the FOAP dataset and source code would be immensely beneficial for my project, providing critical insights and benchmarks.

Thank you for considering my request. I eagerly await the opportunity to further explore and contribute to this exciting field of study. Please feel free to contact me if you need any additional information or have any questions.

**Comment by jflixjtu** [comment]
Done.

**Comment by jflixjtu** [comment]
Done! Please check the email provided to check the invitation.
