### ISSUE TITLE
Request for Access to FOAP Dataset and Source Code for Academic Research

### ISSUE THREAD

**Issue by Rameen-Mahmood** [jflixjtu/FOAP#4]
Hello,

I hope you're doing well. I'm a PhD candidate at New York University, specializing in application and device fingerprinting. I'm writing to request access to the FOAP dataset and source code for academic research purposes. My work intersects closely with your study, and I believe access to these resources would greatly benefit my research in developing models that improve the accuracy of application and device classification. 

I am writing to follow up on my previous submission of a request via the provided Google form. I have not yet received a response and wanted to inquire about the status of my request.

Thank you for considering my request. Any data and code received will be used strictly for academic purposes, adhering to all relevant ethical guidelines and with respect for confidentiality and intellectual property rights.

**Comment by jflixjtu** [comment]
Done
