### ISSUE TITLE
Request for Access to FOAP Dataset and Source Code for Academic Research

### ISSUE THREAD

**Issue by Ivy-0321** [jflixjtu/FOAP#5]
Hello jflixjtu,

I hope this message finds you well. My name is Ivy, and I am a graduate student at UCAS. I am writing to request access to the FOAP dataset and source code for academic research purposes.

I have already filled out the access request form, but unfortunately, I have not received a response yet. Understanding the importance of your project and the potential it holds for my research, I am eager to gain permission to access the relevant resources.I am committed to adhering to any terms and conditions associated with accessing the FOAP dataset and source code. 

I would greatly appreciate it if you could expedite the processing of my request and grant me access at your earliest convenience. If there are any additional steps or information required from my end, please let me know.

Thank you for your time and consideration. I am looking forward to your positive response and the opportunity to contribute to the advancement of knowledge through your valuable project.

Best regards,
Ivy

**Comment by jflixjtu** [comment]
Done
